### ISSUE TITLE
Create Single Gallery Edit Page

### ISSUE THREAD

**Issue by memo330179** [BCStudentSoftwareDevTeam/Ullman_Galleries#2]
This is the page where the Admin can edit the information from galleries. The functionality should be as follows.

- [x] Allow the admin to change the gallery name
- [x] Allow admin to change open date
- [ ] Allow admin to add poster image
- [x] Allow admin to edit description
- [x] Allow admin to save description
- [x] Allow admin to cancel

![gallery_edit](https://user-images.githubusercontent.com/11654721/34920282-54e5f522-f93e-11e7-9996-2c465c8dfdd8.png)

**Comment by agarwali** [comment]
@memo330179 what is the difference between user and admin on this page (eg. first bullet point) Resolved

**Comment by memo330179** [comment]
@agarwali there is no difference. This is an admin only page.

**Comment by agarwali** [comment]
@Jessonsotoventura @memo330179  need more clarity. Here are some scenarios
1. Are we reusing this page for both adding and editing a gallery? If so we can have two possibilities
a. Do we want two different routes for the add and edit pages? This will be easier because we can pass the gid in the route for the edit page.
b. Otherwise, we have to somehow pass the gallery name (possibly through the url, which might not be unique?) to the page and do a get_or_create, leaving the rest of the fields empty by default.

I can implement any case, let me know what you think or if there is a better way.

**Comment by Jessonsotoventura** [comment]
@agarwali Yes it should do both, and I agree that two routes would be easiest, so please take that approach

**Comment by memo330179** [comment]
Pull request open for this. https://github.com/BCStudentSoftwareDevTeam/Ullman_Galleries/pull/15

**Comment by memo330179** [comment]
Things to finish

- [x] Save changes to DB

**Comment by agarwali** [comment]
I was having some dir issues with upload while testing so I have not pushed the upload file for now. Also changed the HTML temporarily so the edit and add functionality can still be tested. Will be looking into the upload issues this evening.

**Comment by agarwali** [comment]
As far as uploads, I have two options working now
1. Have a dropzone upload-form within the form submission, once the file upload is done we send the file dir to the front-end through json and modify the html to set the uploaded images path. Once the entire is submitted we make an entry in the files table. Cons: Need to delete the file if a new image is uploaded and the form is discarded halfway, but also replace it with the old image which gets complicated if the user keeps uploading and discarding. Maybe we keep a temporary folder for the image, but we have to do a lot of os commands.
2. Attach the file upload request with the entire form submission (so only 1 post request) by using custom dropzone configuration. Cons: May take some time to process the request. We have to send "good" error messages to the front-end to let the user know what exactly went wrong in their post request.

Let me know what you guys think. I prefer the second option because dealing with discard becomes easier.

**Comment by agarwali** [comment]
@Jessonsotoventura I have found the issue that is causing the entire form to become dropzone.
1. if we follow [this approach ](https://github.com/enyo/dropzone/wiki/Combine-normal-form-with-Dropzone) then the entire forms becomes a drop zone. We have to change a lot of CSS and JS, so no point of using dropzone.
2. if we make a div into dropzone programmatically, we must provide an [upload URL](http://www.dropzonejs.com/#create-dropzones-programmatically) in the javascript. Now we can no longer have the same upload URL in the form action, otherwise, there will be two posts requests to the same URL. There is a way to get around this by not adding a form action URL but adding the form data programmatically to the file upload in the javascript as seen [here](https://laracasts.com/discuss/channels/general-discussion/dropzonejs-in-a-normal-form?page=1) (post by ccarver). But our front-end code for dropzone will be tied to the form and will not be modular.

Now it is a choice between modularity of front-end (we will have to have separate URL for upload) vs. Keeping the same upload URL for form data and file data (less modular) What do you think?

**Comment by Jessonsotoventura** [comment]
You are right #1 is not worth doing, #2 is better. This has turned into a nice issue huh, well seeing as you and Kenny have each started an independent implementation. The modularity has not really gone well. Given that go ahead and separate it out.

**Comment by Jessonsotoventura** [comment]
V1 is live thank you for your commits
